#ifdef NXNA_GL_LOAD_PROC

#undef NXNA_DECLARE_GL_EXTENSION_20
#undef NXNA_DECLARE_GL_EXTENSION_30
#undef NXNA_DECLARE_GL_EXTENSION_31
#undef NXNA_DECLARE_GL_EXTENSION_32
#undef NXNA_DECLARE_GL_EXTENSION_40
#undef NXNA_DECLARE_GL_EXTENSION_41
#undef NXNA_DECLARE_GL_EXTENSION_42
#undef NXNA_DECLARE_GL_EXTENSION_45
#undef NXNA_DECLARE_GL_EXTENSION
#define NXNA_DECLARE_GL_EXTENSION(vmajor, vminor, p, n) GL_LOAD_PROC(p, n);

#if defined NXNA_DECLARE_EXTENSIONS_45
#define NXNA_DECLARE_GL_EXTENSION_20(p, n)
#define NXNA_DECLARE_GL_EXTENSION_30(p, n)
#define NXNA_DECLARE_GL_EXTENSION_31(p, n) 
#define NXNA_DECLARE_GL_EXTENSION_32(p, n) 
#define NXNA_DECLARE_GL_EXTENSION_40(p, n)
#define NXNA_DECLARE_GL_EXTENSION_41(p, n)
#define NXNA_DECLARE_GL_EXTENSION_42(p, n) 
#define NXNA_DECLARE_GL_EXTENSION_45(p, n) NXNA_DECLARE_GL_EXTENSION(4, 5, p, n)
#elif defined NXNA_DECLARE_EXTENSIONS_42
#define NXNA_DECLARE_GL_EXTENSION_20(p, n)
#define NXNA_DECLARE_GL_EXTENSION_30(p, n)
#define NXNA_DECLARE_GL_EXTENSION_31(p, n) 
#define NXNA_DECLARE_GL_EXTENSION_32(p, n) 
#define NXNA_DECLARE_GL_EXTENSION_40(p, n)
#define NXNA_DECLARE_GL_EXTENSION_41(p, n)
#define NXNA_DECLARE_GL_EXTENSION_42(p, n) NXNA_DECLARE_GL_EXTENSION(4, 2, p, n)
#define NXNA_DECLARE_GL_EXTENSION_45(p, n)
#elif defined NXNA_DECLARE_EXTENSIONS_41
#define NXNA_DECLARE_GL_EXTENSION_20(p, n)
#define NXNA_DECLARE_GL_EXTENSION_30(p, n)
#define NXNA_DECLARE_GL_EXTENSION_31(p, n) 
#define NXNA_DECLARE_GL_EXTENSION_32(p, n) 
#define NXNA_DECLARE_GL_EXTENSION_40(p, n) 
#define NXNA_DECLARE_GL_EXTENSION_41(p, n) NXNA_DECLARE_GL_EXTENSION(4, 1, p, n)
#define NXNA_DECLARE_GL_EXTENSION_42(p, n)
#define NXNA_DECLARE_GL_EXTENSION_45(p, n)
#elif defined NXNA_DECLARE_EXTENSIONS_40
#define NXNA_DECLARE_GL_EXTENSION_20(p, n)
#define NXNA_DECLARE_GL_EXTENSION_30(p, n)
#define NXNA_DECLARE_GL_EXTENSION_31(p, n) 
#define NXNA_DECLARE_GL_EXTENSION_32(p, n) 
#define NXNA_DECLARE_GL_EXTENSION_40(p, n) NXNA_DECLARE_GL_EXTENSION(4, 0, p, n)
#define NXNA_DECLARE_GL_EXTENSION_41(p, n)
#define NXNA_DECLARE_GL_EXTENSION_42(p, n)
#define NXNA_DECLARE_GL_EXTENSION_45(p, n)
#elif defined NXNA_DECLARE_EXTENSIONS_32
#define NXNA_DECLARE_GL_EXTENSION_20(p, n)
#define NXNA_DECLARE_GL_EXTENSION_30(p, n)
#define NXNA_DECLARE_GL_EXTENSION_31(p, n) 
#define NXNA_DECLARE_GL_EXTENSION_32(p, n) NXNA_DECLARE_GL_EXTENSION(3, 2, p, n)
#define NXNA_DECLARE_GL_EXTENSION_40(p, n) 
#define NXNA_DECLARE_GL_EXTENSION_41(p, n)
#define NXNA_DECLARE_GL_EXTENSION_42(p, n)
#define NXNA_DECLARE_GL_EXTENSION_45(p, n)
#elif defined NXNA_DECLARE_EXTENSIONS_31
#define NXNA_DECLARE_GL_EXTENSION_20(p, n)
#define NXNA_DECLARE_GL_EXTENSION_30(p, n)
#define NXNA_DECLARE_GL_EXTENSION_31(p, n) NXNA_DECLARE_GL_EXTENSION(3, 1, p, n)
#define NXNA_DECLARE_GL_EXTENSION_32(p, n)
#define NXNA_DECLARE_GL_EXTENSION_40(p, n) 
#define NXNA_DECLARE_GL_EXTENSION_41(p, n)
#define NXNA_DECLARE_GL_EXTENSION_42(p, n)
#define NXNA_DECLARE_GL_EXTENSION_45(p, n)
#elif defined NXNA_DECLARE_EXTENSIONS_30
#define NXNA_DECLARE_GL_EXTENSION_20(p, n) 
#define NXNA_DECLARE_GL_EXTENSION_30(p, n) NXNA_DECLARE_GL_EXTENSION(3, 0, p, n)
#define NXNA_DECLARE_GL_EXTENSION_31(p, n)
#define NXNA_DECLARE_GL_EXTENSION_32(p, n)
#define NXNA_DECLARE_GL_EXTENSION_40(p, n) 
#define NXNA_DECLARE_GL_EXTENSION_41(p, n)
#define NXNA_DECLARE_GL_EXTENSION_42(p, n)
#define NXNA_DECLARE_GL_EXTENSION_45(p, n)
#elif defined NXNA_DECLARE_EXTENSIONS_20
#define NXNA_DECLARE_GL_EXTENSION_20(p, n) NXNA_DECLARE_GL_EXTENSION(2, 0, p, n)
#define NXNA_DECLARE_GL_EXTENSION_30(p, n)
#define NXNA_DECLARE_GL_EXTENSION_31(p, n)
#define NXNA_DECLARE_GL_EXTENSION_32(p, n)
#define NXNA_DECLARE_GL_EXTENSION_40(p, n) 
#define NXNA_DECLARE_GL_EXTENSION_41(p, n)
#define NXNA_DECLARE_GL_EXTENSION_42(p, n)
#define NXNA_DECLARE_GL_EXTENSION_45(p, n)
#endif
#else
#define NXNA_DECLARE_GL_EXTENSION_20(p, n) NXNA_DECLARE_GL_EXTENSION(2, 0, p, n)
#define NXNA_DECLARE_GL_EXTENSION_30(p, n) NXNA_DECLARE_GL_EXTENSION(3, 0, p, n)
#define NXNA_DECLARE_GL_EXTENSION_31(p, n) NXNA_DECLARE_GL_EXTENSION(3, 1, p, n)
#define NXNA_DECLARE_GL_EXTENSION_32(p, n) NXNA_DECLARE_GL_EXTENSION(3, 2, p, n)
#define NXNA_DECLARE_GL_EXTENSION_40(p, n) NXNA_DECLARE_GL_EXTENSION(4, 0, p, n)
#define NXNA_DECLARE_GL_EXTENSION_41(p, n) NXNA_DECLARE_GL_EXTENSION(4, 1, p, n)
#define NXNA_DECLARE_GL_EXTENSION_42(p, n) NXNA_DECLARE_GL_EXTENSION(4, 2, p, n)
#define NXNA_DECLARE_GL_EXTENSION_45(p, n) NXNA_DECLARE_GL_EXTENSION(4, 5, p, n)
#endif

/* OpenGL 2.0 */
NXNA_DECLARE_GL_EXTENSION_20(PFNGLACTIVETEXTUREPROC, glActiveTexture)
NXNA_DECLARE_GL_EXTENSION_20(PFNGLATTACHSHADERPROC, glAttachShader)
NXNA_DECLARE_GL_EXTENSION_20(PFNGLBINDBUFFERPROC, glBindBuffer)
NXNA_DECLARE_GL_EXTENSION_20(PFNGLBLENDEQUATIONSEPARATEPROC, glBlendEquationSeparate)
NXNA_DECLARE_GL_EXTENSION_20(PFNGLBLENDFUNCSEPARATEPROC, glBlendFuncSeparate)
NXNA_DECLARE_GL_EXTENSION_20(PFNGLBUFFERDATAPROC, glBufferData)
NXNA_DECLARE_GL_EXTENSION_20(PFNGLBUFFERSUBDATAPROC, glBufferSubData)
NXNA_DECLARE_GL_EXTENSION_20(PFNGLCOMPILESHADERPROC, glCompileShader)
NXNA_DECLARE_GL_EXTENSION_20(PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC, glCompressedTexSubImage2D)
NXNA_DECLARE_GL_EXTENSION_20(PFNGLCREATEPROGRAMPROC, glCreateProgram)
NXNA_DECLARE_GL_EXTENSION_20(PFNGLCREATESHADERPROC, glCreateShader)
NXNA_DECLARE_GL_EXTENSION_20(PFNGLDELETEBUFFERSPROC, glDeleteBuffers)
NXNA_DECLARE_GL_EXTENSION_20(PFNGLDELETEPROGRAMPROC, glDeleteProgram)
NXNA_DECLARE_GL_EXTENSION_20(PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray)
NXNA_DECLARE_GL_EXTENSION_20(PFNGLGENBUFFERSPROC, glGenBuffers)
NXNA_DECLARE_GL_EXTENSION_20(PFNGLGETPROGRAMIVPROC, glGetProgramiv)
NXNA_DECLARE_GL_EXTENSION_20(PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog)
NXNA_DECLARE_GL_EXTENSION_20(PFNGLGETSHADERIVPROC, glGetShaderiv)
NXNA_DECLARE_GL_EXTENSION_20(PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog)
NXNA_DECLARE_GL_EXTENSION_20(PFNGLLINKPROGRAMPROC, glLinkProgram)
NXNA_DECLARE_GL_EXTENSION_20(PFNGLSHADERSOURCEPROC, glShaderSource)
NXNA_DECLARE_GL_EXTENSION_20(PFNGLUSEPROGRAMPROC, glUseProgram)
NXNA_DECLARE_GL_EXTENSION_20(PFNGLVERTEXATTRIBPOINTERPROC, glVertexAttribPointer)

/* OpenGL 3.0 */
NXNA_DECLARE_GL_EXTENSION_30(PFNGLBINDBUFFERRANGEPROC, glBindBufferRange)
NXNA_DECLARE_GL_EXTENSION_30(PFNGLBINDVERTEXARRAYPROC, glBindVertexArray)
NXNA_DECLARE_GL_EXTENSION_30(PFNGLCLEARBUFFERFIPROC, glClearBufferfi)
NXNA_DECLARE_GL_EXTENSION_30(PFNGLCLEARBUFFERFVPROC, glClearBufferfv)
NXNA_DECLARE_GL_EXTENSION_30(PFNGLDELETEVERTEXARRAYSPROC, glDeleteVertexArrays)
NXNA_DECLARE_GL_EXTENSION_30(PFNGLDISABLEIPROC, glDisablei)
NXNA_DECLARE_GL_EXTENSION_30(PFNGLENABLEIPROC, glEnablei)
NXNA_DECLARE_GL_EXTENSION_30(PFNGLGENVERTEXARRAYSPROC, glGenVertexArrays)
NXNA_DECLARE_GL_EXTENSION_30(PFNGLGETSTRINGIPROC, glGetStringi)
NXNA_DECLARE_GL_EXTENSION_30(PFNGLMAPBUFFERRANGEPROC, glMapBufferRange)
NXNA_DECLARE_GL_EXTENSION_30(PFNGLUNMAPBUFFERPROC, glUnmapBuffer)

/* OpenGL 3.1 */
NXNA_DECLARE_GL_EXTENSION_31(PFNGLGETUNIFORMBLOCKINDEXPROC, glGetUniformBlockIndex)
NXNA_DECLARE_GL_EXTENSION_31(PFNGLUNIFORMBLOCKBINDINGPROC, glUniformBlockBinding)

/* OpenGL 3.2 */
NXNA_DECLARE_GL_EXTENSION_32(PFNGLDRAWELEMENTSBASEVERTEXPROC, glDrawElementsBaseVertex)

/* OpenGL 4.0 */
NXNA_DECLARE_GL_EXTENSION_40(PFNGLBLENDEQUATIONSEPARATEIPROC, glBlendEquationSeparatei)
NXNA_DECLARE_GL_EXTENSION_40(PFNGLBLENDFUNCSEPARATEIPROC, glBlendFuncSeparatei)

/* OpenGL 4.1 */
NXNA_DECLARE_GL_EXTENSION_41(PFNGLBINDPROGRAMPIPELINEPROC, glBindProgramPipeline)
NXNA_DECLARE_GL_EXTENSION_41(PFNGLCREATESHADERPROGRAMVPROC, glCreateShaderProgramv)
NXNA_DECLARE_GL_EXTENSION_41(PFNGLDELETEPROGRAMPIPELINESPROC, glDeleteProgramPipelines)
NXNA_DECLARE_GL_EXTENSION_41(PFNGLGENPROGRAMPIPELINESPROC, glGenProgramPipelines)
NXNA_DECLARE_GL_EXTENSION_41(PFNGLUSEPROGRAMSTAGESPROC, glUseProgramStages)

/* OpenGL 4.2 */
NXNA_DECLARE_GL_EXTENSION_42(PFNGLTEXSTORAGE2DPROC, glTexStorage2D)

/* OpenGL 4.5 */
NXNA_DECLARE_GL_EXTENSION_45(PFNGLBINDTEXTUREUNITPROC, glBindTextureUnit);
NXNA_DECLARE_GL_EXTENSION_45(PFNGLCOMPRESSEDTEXTURESUBIMAGE2DPROC, glCompressedTextureSubImage2D);
NXNA_DECLARE_GL_EXTENSION_45(PFNGLCREATEBUFFERSPROC, glCreateBuffers);
NXNA_DECLARE_GL_EXTENSION_45(PFNGLCREATETEXTURESPROC, glCreateTextures);
NXNA_DECLARE_GL_EXTENSION_45(PFNGLCREATEVERTEXARRAYSPROC, glCreateVertexArrays);
NXNA_DECLARE_GL_EXTENSION_45(PFNGLENABLEVERTEXARRAYATTRIBPROC, glEnableVertexArrayAttrib);
NXNA_DECLARE_GL_EXTENSION_45(PFNGLMAPNAMEDBUFFERPROC, glMapNamedBuffer);
NXNA_DECLARE_GL_EXTENSION_45(PFNGLMAPNAMEDBUFFERRANGEPROC, glMapNamedBufferRange);
NXNA_DECLARE_GL_EXTENSION_45(PFNGLNAMEDBUFFERDATAPROC, glNamedBufferStorage);
NXNA_DECLARE_GL_EXTENSION_45(PFNGLTEXTURESTORAGE2DPROC, glTextureStorage2D);
NXNA_DECLARE_GL_EXTENSION_45(PFNGLTEXTURESUBIMAGE2DPROC, glTextureSubImage2D);
NXNA_DECLARE_GL_EXTENSION_45(PFNGLUNMAPNAMEDBUFFERPROC, glUnmapNamedBuffer);
NXNA_DECLARE_GL_EXTENSION_45(PFNGLVERTEXARRAYATTRIBBINDINGPROC, glVertexArrayAttribBinding);
NXNA_DECLARE_GL_EXTENSION_45(PFNGLVERTEXARRAYATTRIBFORMATPROC, glVertexArrayAttribFormat);
NXNA_DECLARE_GL_EXTENSION_45(PFNGLVERTEXARRAYVERTEXBUFFERPROC, glVertexArrayVertexBuffer);